// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	hotmethod "minidrop/apiserver/proto/hotmethod"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateTask：apiserver 向 drop_server 下发一个新任务。
// drop_server 把 TaskDesc 放进对应 Agent IP 的任务队列，等 Agent 心跳时取走。
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIp      string                 `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"` // 目标 Agent 的 IP 地址
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                   // 服务名，固定填 "hotmethod"
	TaskDesc      *hotmethod.TaskDesc    `protobuf:"bytes,3,opt,name=task_desc,json=taskDesc,proto3" json:"task_desc,omitempty"` // 完整的任务描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *CreateTaskRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskDesc() *hotmethod.TaskDesc {
	if x != nil {
		return x.TaskDesc
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 失败时的原因描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FetchData：apiserver 查询某个任务的采集结果（cos_key）。
type FetchDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataRequest) Reset() {
	*x = FetchDataRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataRequest) ProtoMessage() {}

func (x *FetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataRequest.ProtoReflect.Descriptor instead.
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *FetchDataRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FetchDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CosKey        string                 `protobuf:"bytes,2,opt,name=cos_key,json=cosKey,proto3" json:"cos_key,omitempty"`                   // 结果文件在对象存储中的路径
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 失败时的原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataResponse) Reset() {
	*x = FetchDataResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResponse) ProtoMessage() {}

func (x *FetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResponse.ProtoReflect.Descriptor instead.
func (*FetchDataResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *FetchDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchDataResponse) GetCosKey() string {
	if x != nil {
		return x.CosKey
	}
	return ""
}

func (x *FetchDataResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StatAgent：apiserver 查询某个 Agent 当前的资源占用情况。
// 用于前端 "Agent 详情" 页面的实时资源展示。
type StatAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddr        string                 `protobuf:"bytes,1,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"` // 要查询的 Agent IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatAgentRequest) Reset() {
	*x = StatAgentRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatAgentRequest) ProtoMessage() {}

func (x *StatAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatAgentRequest.ProtoReflect.Descriptor instead.
func (*StatAgentRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *StatAgentRequest) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

type StatAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`                                   // Agent 是否在线
	CpuPercent    float32                `protobuf:"fixed32,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`        // Agent 进程当前 CPU 使用率
	RssKb         uint64                 `protobuf:"varint,3,opt,name=rss_kb,json=rssKb,proto3" json:"rss_kb,omitempty"`                        // Agent 进程当前内存占用（KB）
	LastHeartbeat string                 `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // 最后一次心跳时间（RFC3339 格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatAgentResponse) Reset() {
	*x = StatAgentResponse{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatAgentResponse) ProtoMessage() {}

func (x *StatAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatAgentResponse.ProtoReflect.Descriptor instead.
func (*StatAgentResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *StatAgentResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *StatAgentResponse) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatAgentResponse) GetRssKb() uint64 {
	if x != nil {
		return x.RssKb
	}
	return 0
}

func (x *StatAgentResponse) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\x1a\x0fhotmethod.proto\"|\n" +
	"\x11CreateTaskRequest\x12\x1b\n" +
	"\ttarget_ip\x18\x01 \x01(\tR\btargetIp\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x120\n" +
	"\ttask_desc\x18\x03 \x01(\v2\x13.hotmethod.TaskDescR\btaskDesc\"H\n" +
	"\x12CreateTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10FetchDataRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"k\n" +
	"\x11FetchDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\acos_key\x18\x02 \x01(\tR\x06cosKey\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"+\n" +
	"\x10StatAgentRequest\x12\x17\n" +
	"\aip_addr\x18\x01 \x01(\tR\x06ipAddr\"\x8a\x01\n" +
	"\x11StatAgentResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x02R\n" +
	"cpuPercent\x12\x15\n" +
	"\x06rss_kb\x18\x03 \x01(\x04R\x05rssKb\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\tR\rlastHeartbeat2\xd8\x01\n" +
	"\aControl\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.control.CreateTaskRequest\x1a\x1b.control.CreateTaskResponse\x12B\n" +
	"\tFetchData\x12\x19.control.FetchDataRequest\x1a\x1a.control.FetchDataResponse\x12B\n" +
	"\tStatAgent\x12\x19.control.StatAgentRequest\x1a\x1a.control.StatAgentResponseB\"Z minidrop/apiserver/proto/controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_control_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),  // 0: control.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 1: control.CreateTaskResponse
	(*FetchDataRequest)(nil),   // 2: control.FetchDataRequest
	(*FetchDataResponse)(nil),  // 3: control.FetchDataResponse
	(*StatAgentRequest)(nil),   // 4: control.StatAgentRequest
	(*StatAgentResponse)(nil),  // 5: control.StatAgentResponse
	(*hotmethod.TaskDesc)(nil), // 6: hotmethod.TaskDesc
}
var file_control_proto_depIdxs = []int32{
	6, // 0: control.CreateTaskRequest.task_desc:type_name -> hotmethod.TaskDesc
	0, // 1: control.Control.CreateTask:input_type -> control.CreateTaskRequest
	2, // 2: control.Control.FetchData:input_type -> control.FetchDataRequest
	4, // 3: control.Control.StatAgent:input_type -> control.StatAgentRequest
	1, // 4: control.Control.CreateTask:output_type -> control.CreateTaskResponse
	3, // 5: control.Control.FetchData:output_type -> control.FetchDataResponse
	5, // 6: control.Control.StatAgent:output_type -> control.StatAgentResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
