// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_common_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_common_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_common_2eproto;
namespace drop {
class CosConfig;
class CosConfigDefaultTypeInternal;
extern CosConfigDefaultTypeInternal _CosConfig_default_instance_;
class File;
class FileDefaultTypeInternal;
extern FileDefaultTypeInternal _File_default_instance_;
class PidStats;
class PidStatsDefaultTypeInternal;
extern PidStatsDefaultTypeInternal _PidStats_default_instance_;
}  // namespace drop
PROTOBUF_NAMESPACE_OPEN
template<> ::drop::CosConfig* Arena::CreateMaybeMessage<::drop::CosConfig>(Arena*);
template<> ::drop::File* Arena::CreateMaybeMessage<::drop::File>(Arena*);
template<> ::drop::PidStats* Arena::CreateMaybeMessage<::drop::PidStats>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace drop {

// ===================================================================

class PidStats PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:drop.PidStats) */ {
 public:
  inline PidStats() : PidStats(nullptr) {};
  virtual ~PidStats();

  PidStats(const PidStats& from);
  PidStats(PidStats&& from) noexcept
    : PidStats() {
    *this = ::std::move(from);
  }

  inline PidStats& operator=(const PidStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline PidStats& operator=(PidStats&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PidStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PidStats* internal_default_instance() {
    return reinterpret_cast<const PidStats*>(
               &_PidStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PidStats& a, PidStats& b) {
    a.Swap(&b);
  }
  inline void Swap(PidStats* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PidStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PidStats* New() const final {
    return CreateMaybeMessage<PidStats>(nullptr);
  }

  PidStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PidStats>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PidStats& from);
  void MergeFrom(const PidStats& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PidStats* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "drop.PidStats";
  }
  protected:
  explicit PidStats(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_common_2eproto);
    return ::descriptor_table_common_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPidFieldNumber = 1,
    kCpuPercentFieldNumber = 2,
    kRssKbFieldNumber = 3,
    kReadKbFieldNumber = 4,
    kWriteKbFieldNumber = 5,
  };
  // int32 pid = 1;
  void clear_pid();
  ::PROTOBUF_NAMESPACE_ID::int32 pid() const;
  void set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pid() const;
  void _internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float cpu_percent = 2;
  void clear_cpu_percent();
  float cpu_percent() const;
  void set_cpu_percent(float value);
  private:
  float _internal_cpu_percent() const;
  void _internal_set_cpu_percent(float value);
  public:

  // uint64 rss_kb = 3;
  void clear_rss_kb();
  ::PROTOBUF_NAMESPACE_ID::uint64 rss_kb() const;
  void set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_rss_kb() const;
  void _internal_set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 read_kb = 4;
  void clear_read_kb();
  ::PROTOBUF_NAMESPACE_ID::uint64 read_kb() const;
  void set_read_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_read_kb() const;
  void _internal_set_read_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 write_kb = 5;
  void clear_write_kb();
  ::PROTOBUF_NAMESPACE_ID::uint64 write_kb() const;
  void set_write_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_write_kb() const;
  void _internal_set_write_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:drop.PidStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 pid_;
  float cpu_percent_;
  ::PROTOBUF_NAMESPACE_ID::uint64 rss_kb_;
  ::PROTOBUF_NAMESPACE_ID::uint64 read_kb_;
  ::PROTOBUF_NAMESPACE_ID::uint64 write_kb_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_common_2eproto;
};
// -------------------------------------------------------------------

class File PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:drop.File) */ {
 public:
  inline File() : File(nullptr) {};
  virtual ~File();

  File(const File& from);
  File(File&& from) noexcept
    : File() {
    *this = ::std::move(from);
  }

  inline File& operator=(const File& from) {
    CopyFrom(from);
    return *this;
  }
  inline File& operator=(File&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const File& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const File* internal_default_instance() {
    return reinterpret_cast<const File*>(
               &_File_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(File& a, File& b) {
    a.Swap(&b);
  }
  inline void Swap(File* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(File* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline File* New() const final {
    return CreateMaybeMessage<File>(nullptr);
  }

  File* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<File>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const File& from);
  void MergeFrom(const File& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(File* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "drop.File";
  }
  protected:
  explicit File(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_common_2eproto);
    return ::descriptor_table_common_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kContentFieldNumber = 2,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_filename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_filename(
      std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // bytes content = 2;
  void clear_content();
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_content();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_content(
      std::string* content);
  private:
  const std::string& _internal_content() const;
  void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // @@protoc_insertion_point(class_scope:drop.File)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_common_2eproto;
};
// -------------------------------------------------------------------

class CosConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:drop.CosConfig) */ {
 public:
  inline CosConfig() : CosConfig(nullptr) {};
  virtual ~CosConfig();

  CosConfig(const CosConfig& from);
  CosConfig(CosConfig&& from) noexcept
    : CosConfig() {
    *this = ::std::move(from);
  }

  inline CosConfig& operator=(const CosConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline CosConfig& operator=(CosConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CosConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CosConfig* internal_default_instance() {
    return reinterpret_cast<const CosConfig*>(
               &_CosConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CosConfig& a, CosConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(CosConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CosConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CosConfig* New() const final {
    return CreateMaybeMessage<CosConfig>(nullptr);
  }

  CosConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CosConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CosConfig& from);
  void MergeFrom(const CosConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CosConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "drop.CosConfig";
  }
  protected:
  explicit CosConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_common_2eproto);
    return ::descriptor_table_common_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEndpointFieldNumber = 1,
    kBucketFieldNumber = 2,
    kAccessKeyFieldNumber = 3,
    kSecretKeyFieldNumber = 4,
    kUseSslFieldNumber = 5,
  };
  // string endpoint = 1;
  void clear_endpoint();
  const std::string& endpoint() const;
  void set_endpoint(const std::string& value);
  void set_endpoint(std::string&& value);
  void set_endpoint(const char* value);
  void set_endpoint(const char* value, size_t size);
  std::string* mutable_endpoint();
  std::string* release_endpoint();
  void set_allocated_endpoint(std::string* endpoint);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_endpoint();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_endpoint(
      std::string* endpoint);
  private:
  const std::string& _internal_endpoint() const;
  void _internal_set_endpoint(const std::string& value);
  std::string* _internal_mutable_endpoint();
  public:

  // string bucket = 2;
  void clear_bucket();
  const std::string& bucket() const;
  void set_bucket(const std::string& value);
  void set_bucket(std::string&& value);
  void set_bucket(const char* value);
  void set_bucket(const char* value, size_t size);
  std::string* mutable_bucket();
  std::string* release_bucket();
  void set_allocated_bucket(std::string* bucket);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_bucket();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_bucket(
      std::string* bucket);
  private:
  const std::string& _internal_bucket() const;
  void _internal_set_bucket(const std::string& value);
  std::string* _internal_mutable_bucket();
  public:

  // string access_key = 3;
  void clear_access_key();
  const std::string& access_key() const;
  void set_access_key(const std::string& value);
  void set_access_key(std::string&& value);
  void set_access_key(const char* value);
  void set_access_key(const char* value, size_t size);
  std::string* mutable_access_key();
  std::string* release_access_key();
  void set_allocated_access_key(std::string* access_key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_access_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_access_key(
      std::string* access_key);
  private:
  const std::string& _internal_access_key() const;
  void _internal_set_access_key(const std::string& value);
  std::string* _internal_mutable_access_key();
  public:

  // string secret_key = 4;
  void clear_secret_key();
  const std::string& secret_key() const;
  void set_secret_key(const std::string& value);
  void set_secret_key(std::string&& value);
  void set_secret_key(const char* value);
  void set_secret_key(const char* value, size_t size);
  std::string* mutable_secret_key();
  std::string* release_secret_key();
  void set_allocated_secret_key(std::string* secret_key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_secret_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_secret_key(
      std::string* secret_key);
  private:
  const std::string& _internal_secret_key() const;
  void _internal_set_secret_key(const std::string& value);
  std::string* _internal_mutable_secret_key();
  public:

  // bool use_ssl = 5;
  void clear_use_ssl();
  bool use_ssl() const;
  void set_use_ssl(bool value);
  private:
  bool _internal_use_ssl() const;
  void _internal_set_use_ssl(bool value);
  public:

  // @@protoc_insertion_point(class_scope:drop.CosConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr endpoint_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bucket_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr access_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr secret_key_;
  bool use_ssl_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_common_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PidStats

// int32 pid = 1;
inline void PidStats::clear_pid() {
  pid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PidStats::_internal_pid() const {
  return pid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PidStats::pid() const {
  // @@protoc_insertion_point(field_get:drop.PidStats.pid)
  return _internal_pid();
}
inline void PidStats::_internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pid_ = value;
}
inline void PidStats::set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:drop.PidStats.pid)
}

// float cpu_percent = 2;
inline void PidStats::clear_cpu_percent() {
  cpu_percent_ = 0;
}
inline float PidStats::_internal_cpu_percent() const {
  return cpu_percent_;
}
inline float PidStats::cpu_percent() const {
  // @@protoc_insertion_point(field_get:drop.PidStats.cpu_percent)
  return _internal_cpu_percent();
}
inline void PidStats::_internal_set_cpu_percent(float value) {
  
  cpu_percent_ = value;
}
inline void PidStats::set_cpu_percent(float value) {
  _internal_set_cpu_percent(value);
  // @@protoc_insertion_point(field_set:drop.PidStats.cpu_percent)
}

// uint64 rss_kb = 3;
inline void PidStats::clear_rss_kb() {
  rss_kb_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::_internal_rss_kb() const {
  return rss_kb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::rss_kb() const {
  // @@protoc_insertion_point(field_get:drop.PidStats.rss_kb)
  return _internal_rss_kb();
}
inline void PidStats::_internal_set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  rss_kb_ = value;
}
inline void PidStats::set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_rss_kb(value);
  // @@protoc_insertion_point(field_set:drop.PidStats.rss_kb)
}

// uint64 read_kb = 4;
inline void PidStats::clear_read_kb() {
  read_kb_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::_internal_read_kb() const {
  return read_kb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::read_kb() const {
  // @@protoc_insertion_point(field_get:drop.PidStats.read_kb)
  return _internal_read_kb();
}
inline void PidStats::_internal_set_read_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  read_kb_ = value;
}
inline void PidStats::set_read_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_read_kb(value);
  // @@protoc_insertion_point(field_set:drop.PidStats.read_kb)
}

// uint64 write_kb = 5;
inline void PidStats::clear_write_kb() {
  write_kb_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::_internal_write_kb() const {
  return write_kb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PidStats::write_kb() const {
  // @@protoc_insertion_point(field_get:drop.PidStats.write_kb)
  return _internal_write_kb();
}
inline void PidStats::_internal_set_write_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  write_kb_ = value;
}
inline void PidStats::set_write_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_write_kb(value);
  // @@protoc_insertion_point(field_set:drop.PidStats.write_kb)
}

// -------------------------------------------------------------------

// File

// string filename = 1;
inline void File::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& File::filename() const {
  // @@protoc_insertion_point(field_get:drop.File.filename)
  return _internal_filename();
}
inline void File::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:drop.File.filename)
}
inline std::string* File::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:drop.File.filename)
  return _internal_mutable_filename();
}
inline const std::string& File::_internal_filename() const {
  return filename_.Get();
}
inline void File::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void File::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.File.filename)
}
inline void File::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.File.filename)
}
inline void File::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.File.filename)
}
inline std::string* File::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* File::release_filename() {
  // @@protoc_insertion_point(field_release:drop.File.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void File::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.File.filename)
}
inline std::string* File::unsafe_arena_release_filename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.File.filename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return filename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void File::unsafe_arena_set_allocated_filename(
    std::string* filename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      filename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.File.filename)
}

// bytes content = 2;
inline void File::clear_content() {
  content_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& File::content() const {
  // @@protoc_insertion_point(field_get:drop.File.content)
  return _internal_content();
}
inline void File::set_content(const std::string& value) {
  _internal_set_content(value);
  // @@protoc_insertion_point(field_set:drop.File.content)
}
inline std::string* File::mutable_content() {
  // @@protoc_insertion_point(field_mutable:drop.File.content)
  return _internal_mutable_content();
}
inline const std::string& File::_internal_content() const {
  return content_.Get();
}
inline void File::_internal_set_content(const std::string& value) {
  
  content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void File::set_content(std::string&& value) {
  
  content_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.File.content)
}
inline void File::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.File.content)
}
inline void File::set_content(const void* value,
    size_t size) {
  
  content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.File.content)
}
inline std::string* File::_internal_mutable_content() {
  
  return content_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* File::release_content() {
  // @@protoc_insertion_point(field_release:drop.File.content)
  return content_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void File::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.File.content)
}
inline std::string* File::unsafe_arena_release_content() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.File.content)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return content_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void File::unsafe_arena_set_allocated_content(
    std::string* content) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (content != nullptr) {
    
  } else {
    
  }
  content_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      content, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.File.content)
}

// -------------------------------------------------------------------

// CosConfig

// string endpoint = 1;
inline void CosConfig::clear_endpoint() {
  endpoint_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CosConfig::endpoint() const {
  // @@protoc_insertion_point(field_get:drop.CosConfig.endpoint)
  return _internal_endpoint();
}
inline void CosConfig::set_endpoint(const std::string& value) {
  _internal_set_endpoint(value);
  // @@protoc_insertion_point(field_set:drop.CosConfig.endpoint)
}
inline std::string* CosConfig::mutable_endpoint() {
  // @@protoc_insertion_point(field_mutable:drop.CosConfig.endpoint)
  return _internal_mutable_endpoint();
}
inline const std::string& CosConfig::_internal_endpoint() const {
  return endpoint_.Get();
}
inline void CosConfig::_internal_set_endpoint(const std::string& value) {
  
  endpoint_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CosConfig::set_endpoint(std::string&& value) {
  
  endpoint_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.CosConfig.endpoint)
}
inline void CosConfig::set_endpoint(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  endpoint_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.CosConfig.endpoint)
}
inline void CosConfig::set_endpoint(const char* value,
    size_t size) {
  
  endpoint_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.CosConfig.endpoint)
}
inline std::string* CosConfig::_internal_mutable_endpoint() {
  
  return endpoint_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CosConfig::release_endpoint() {
  // @@protoc_insertion_point(field_release:drop.CosConfig.endpoint)
  return endpoint_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CosConfig::set_allocated_endpoint(std::string* endpoint) {
  if (endpoint != nullptr) {
    
  } else {
    
  }
  endpoint_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), endpoint,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.CosConfig.endpoint)
}
inline std::string* CosConfig::unsafe_arena_release_endpoint() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.CosConfig.endpoint)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return endpoint_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CosConfig::unsafe_arena_set_allocated_endpoint(
    std::string* endpoint) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (endpoint != nullptr) {
    
  } else {
    
  }
  endpoint_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      endpoint, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.CosConfig.endpoint)
}

// string bucket = 2;
inline void CosConfig::clear_bucket() {
  bucket_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CosConfig::bucket() const {
  // @@protoc_insertion_point(field_get:drop.CosConfig.bucket)
  return _internal_bucket();
}
inline void CosConfig::set_bucket(const std::string& value) {
  _internal_set_bucket(value);
  // @@protoc_insertion_point(field_set:drop.CosConfig.bucket)
}
inline std::string* CosConfig::mutable_bucket() {
  // @@protoc_insertion_point(field_mutable:drop.CosConfig.bucket)
  return _internal_mutable_bucket();
}
inline const std::string& CosConfig::_internal_bucket() const {
  return bucket_.Get();
}
inline void CosConfig::_internal_set_bucket(const std::string& value) {
  
  bucket_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CosConfig::set_bucket(std::string&& value) {
  
  bucket_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.CosConfig.bucket)
}
inline void CosConfig::set_bucket(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  bucket_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.CosConfig.bucket)
}
inline void CosConfig::set_bucket(const char* value,
    size_t size) {
  
  bucket_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.CosConfig.bucket)
}
inline std::string* CosConfig::_internal_mutable_bucket() {
  
  return bucket_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CosConfig::release_bucket() {
  // @@protoc_insertion_point(field_release:drop.CosConfig.bucket)
  return bucket_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CosConfig::set_allocated_bucket(std::string* bucket) {
  if (bucket != nullptr) {
    
  } else {
    
  }
  bucket_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bucket,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.CosConfig.bucket)
}
inline std::string* CosConfig::unsafe_arena_release_bucket() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.CosConfig.bucket)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return bucket_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CosConfig::unsafe_arena_set_allocated_bucket(
    std::string* bucket) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (bucket != nullptr) {
    
  } else {
    
  }
  bucket_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      bucket, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.CosConfig.bucket)
}

// string access_key = 3;
inline void CosConfig::clear_access_key() {
  access_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CosConfig::access_key() const {
  // @@protoc_insertion_point(field_get:drop.CosConfig.access_key)
  return _internal_access_key();
}
inline void CosConfig::set_access_key(const std::string& value) {
  _internal_set_access_key(value);
  // @@protoc_insertion_point(field_set:drop.CosConfig.access_key)
}
inline std::string* CosConfig::mutable_access_key() {
  // @@protoc_insertion_point(field_mutable:drop.CosConfig.access_key)
  return _internal_mutable_access_key();
}
inline const std::string& CosConfig::_internal_access_key() const {
  return access_key_.Get();
}
inline void CosConfig::_internal_set_access_key(const std::string& value) {
  
  access_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CosConfig::set_access_key(std::string&& value) {
  
  access_key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.CosConfig.access_key)
}
inline void CosConfig::set_access_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  access_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.CosConfig.access_key)
}
inline void CosConfig::set_access_key(const char* value,
    size_t size) {
  
  access_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.CosConfig.access_key)
}
inline std::string* CosConfig::_internal_mutable_access_key() {
  
  return access_key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CosConfig::release_access_key() {
  // @@protoc_insertion_point(field_release:drop.CosConfig.access_key)
  return access_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CosConfig::set_allocated_access_key(std::string* access_key) {
  if (access_key != nullptr) {
    
  } else {
    
  }
  access_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), access_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.CosConfig.access_key)
}
inline std::string* CosConfig::unsafe_arena_release_access_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.CosConfig.access_key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return access_key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CosConfig::unsafe_arena_set_allocated_access_key(
    std::string* access_key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (access_key != nullptr) {
    
  } else {
    
  }
  access_key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      access_key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.CosConfig.access_key)
}

// string secret_key = 4;
inline void CosConfig::clear_secret_key() {
  secret_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CosConfig::secret_key() const {
  // @@protoc_insertion_point(field_get:drop.CosConfig.secret_key)
  return _internal_secret_key();
}
inline void CosConfig::set_secret_key(const std::string& value) {
  _internal_set_secret_key(value);
  // @@protoc_insertion_point(field_set:drop.CosConfig.secret_key)
}
inline std::string* CosConfig::mutable_secret_key() {
  // @@protoc_insertion_point(field_mutable:drop.CosConfig.secret_key)
  return _internal_mutable_secret_key();
}
inline const std::string& CosConfig::_internal_secret_key() const {
  return secret_key_.Get();
}
inline void CosConfig::_internal_set_secret_key(const std::string& value) {
  
  secret_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CosConfig::set_secret_key(std::string&& value) {
  
  secret_key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:drop.CosConfig.secret_key)
}
inline void CosConfig::set_secret_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  secret_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:drop.CosConfig.secret_key)
}
inline void CosConfig::set_secret_key(const char* value,
    size_t size) {
  
  secret_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:drop.CosConfig.secret_key)
}
inline std::string* CosConfig::_internal_mutable_secret_key() {
  
  return secret_key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CosConfig::release_secret_key() {
  // @@protoc_insertion_point(field_release:drop.CosConfig.secret_key)
  return secret_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CosConfig::set_allocated_secret_key(std::string* secret_key) {
  if (secret_key != nullptr) {
    
  } else {
    
  }
  secret_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), secret_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:drop.CosConfig.secret_key)
}
inline std::string* CosConfig::unsafe_arena_release_secret_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:drop.CosConfig.secret_key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return secret_key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CosConfig::unsafe_arena_set_allocated_secret_key(
    std::string* secret_key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (secret_key != nullptr) {
    
  } else {
    
  }
  secret_key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      secret_key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:drop.CosConfig.secret_key)
}

// bool use_ssl = 5;
inline void CosConfig::clear_use_ssl() {
  use_ssl_ = false;
}
inline bool CosConfig::_internal_use_ssl() const {
  return use_ssl_;
}
inline bool CosConfig::use_ssl() const {
  // @@protoc_insertion_point(field_get:drop.CosConfig.use_ssl)
  return _internal_use_ssl();
}
inline void CosConfig::_internal_set_use_ssl(bool value) {
  
  use_ssl_ = value;
}
inline void CosConfig::set_use_ssl(bool value) {
  _internal_set_use_ssl(value);
  // @@protoc_insertion_point(field_set:drop.CosConfig.use_ssl)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace drop

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_common_2eproto
