// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "hotmethod.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_2eproto;
namespace control {
class CreateTaskRequest;
class CreateTaskRequestDefaultTypeInternal;
extern CreateTaskRequestDefaultTypeInternal _CreateTaskRequest_default_instance_;
class CreateTaskResponse;
class CreateTaskResponseDefaultTypeInternal;
extern CreateTaskResponseDefaultTypeInternal _CreateTaskResponse_default_instance_;
class FetchDataRequest;
class FetchDataRequestDefaultTypeInternal;
extern FetchDataRequestDefaultTypeInternal _FetchDataRequest_default_instance_;
class FetchDataResponse;
class FetchDataResponseDefaultTypeInternal;
extern FetchDataResponseDefaultTypeInternal _FetchDataResponse_default_instance_;
class StatAgentRequest;
class StatAgentRequestDefaultTypeInternal;
extern StatAgentRequestDefaultTypeInternal _StatAgentRequest_default_instance_;
class StatAgentResponse;
class StatAgentResponseDefaultTypeInternal;
extern StatAgentResponseDefaultTypeInternal _StatAgentResponse_default_instance_;
}  // namespace control
PROTOBUF_NAMESPACE_OPEN
template<> ::control::CreateTaskRequest* Arena::CreateMaybeMessage<::control::CreateTaskRequest>(Arena*);
template<> ::control::CreateTaskResponse* Arena::CreateMaybeMessage<::control::CreateTaskResponse>(Arena*);
template<> ::control::FetchDataRequest* Arena::CreateMaybeMessage<::control::FetchDataRequest>(Arena*);
template<> ::control::FetchDataResponse* Arena::CreateMaybeMessage<::control::FetchDataResponse>(Arena*);
template<> ::control::StatAgentRequest* Arena::CreateMaybeMessage<::control::StatAgentRequest>(Arena*);
template<> ::control::StatAgentResponse* Arena::CreateMaybeMessage<::control::StatAgentResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace control {

// ===================================================================

class CreateTaskRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.CreateTaskRequest) */ {
 public:
  inline CreateTaskRequest() : CreateTaskRequest(nullptr) {};
  virtual ~CreateTaskRequest();

  CreateTaskRequest(const CreateTaskRequest& from);
  CreateTaskRequest(CreateTaskRequest&& from) noexcept
    : CreateTaskRequest() {
    *this = ::std::move(from);
  }

  inline CreateTaskRequest& operator=(const CreateTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateTaskRequest& operator=(CreateTaskRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreateTaskRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateTaskRequest* internal_default_instance() {
    return reinterpret_cast<const CreateTaskRequest*>(
               &_CreateTaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreateTaskRequest& a, CreateTaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateTaskRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateTaskRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreateTaskRequest* New() const final {
    return CreateMaybeMessage<CreateTaskRequest>(nullptr);
  }

  CreateTaskRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreateTaskRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreateTaskRequest& from);
  void MergeFrom(const CreateTaskRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateTaskRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.CreateTaskRequest";
  }
  protected:
  explicit CreateTaskRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetIpFieldNumber = 1,
    kServiceFieldNumber = 2,
    kTaskDescFieldNumber = 3,
  };
  // string target_ip = 1;
  void clear_target_ip();
  const std::string& target_ip() const;
  void set_target_ip(const std::string& value);
  void set_target_ip(std::string&& value);
  void set_target_ip(const char* value);
  void set_target_ip(const char* value, size_t size);
  std::string* mutable_target_ip();
  std::string* release_target_ip();
  void set_allocated_target_ip(std::string* target_ip);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_target_ip();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_target_ip(
      std::string* target_ip);
  private:
  const std::string& _internal_target_ip() const;
  void _internal_set_target_ip(const std::string& value);
  std::string* _internal_mutable_target_ip();
  public:

  // string service = 2;
  void clear_service();
  const std::string& service() const;
  void set_service(const std::string& value);
  void set_service(std::string&& value);
  void set_service(const char* value);
  void set_service(const char* value, size_t size);
  std::string* mutable_service();
  std::string* release_service();
  void set_allocated_service(std::string* service);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_service();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_service(
      std::string* service);
  private:
  const std::string& _internal_service() const;
  void _internal_set_service(const std::string& value);
  std::string* _internal_mutable_service();
  public:

  // .hotmethod.TaskDesc task_desc = 3;
  bool has_task_desc() const;
  private:
  bool _internal_has_task_desc() const;
  public:
  void clear_task_desc();
  const ::hotmethod::TaskDesc& task_desc() const;
  ::hotmethod::TaskDesc* release_task_desc();
  ::hotmethod::TaskDesc* mutable_task_desc();
  void set_allocated_task_desc(::hotmethod::TaskDesc* task_desc);
  private:
  const ::hotmethod::TaskDesc& _internal_task_desc() const;
  ::hotmethod::TaskDesc* _internal_mutable_task_desc();
  public:
  void unsafe_arena_set_allocated_task_desc(
      ::hotmethod::TaskDesc* task_desc);
  ::hotmethod::TaskDesc* unsafe_arena_release_task_desc();

  // @@protoc_insertion_point(class_scope:control.CreateTaskRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_ip_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_;
  ::hotmethod::TaskDesc* task_desc_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// -------------------------------------------------------------------

class CreateTaskResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.CreateTaskResponse) */ {
 public:
  inline CreateTaskResponse() : CreateTaskResponse(nullptr) {};
  virtual ~CreateTaskResponse();

  CreateTaskResponse(const CreateTaskResponse& from);
  CreateTaskResponse(CreateTaskResponse&& from) noexcept
    : CreateTaskResponse() {
    *this = ::std::move(from);
  }

  inline CreateTaskResponse& operator=(const CreateTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateTaskResponse& operator=(CreateTaskResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreateTaskResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateTaskResponse* internal_default_instance() {
    return reinterpret_cast<const CreateTaskResponse*>(
               &_CreateTaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CreateTaskResponse& a, CreateTaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateTaskResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateTaskResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreateTaskResponse* New() const final {
    return CreateMaybeMessage<CreateTaskResponse>(nullptr);
  }

  CreateTaskResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreateTaskResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreateTaskResponse& from);
  void MergeFrom(const CreateTaskResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateTaskResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.CreateTaskResponse";
  }
  protected:
  explicit CreateTaskResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:control.CreateTaskResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// -------------------------------------------------------------------

class FetchDataRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.FetchDataRequest) */ {
 public:
  inline FetchDataRequest() : FetchDataRequest(nullptr) {};
  virtual ~FetchDataRequest();

  FetchDataRequest(const FetchDataRequest& from);
  FetchDataRequest(FetchDataRequest&& from) noexcept
    : FetchDataRequest() {
    *this = ::std::move(from);
  }

  inline FetchDataRequest& operator=(const FetchDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchDataRequest& operator=(FetchDataRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchDataRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchDataRequest* internal_default_instance() {
    return reinterpret_cast<const FetchDataRequest*>(
               &_FetchDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FetchDataRequest& a, FetchDataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchDataRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchDataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchDataRequest* New() const final {
    return CreateMaybeMessage<FetchDataRequest>(nullptr);
  }

  FetchDataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchDataRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchDataRequest& from);
  void MergeFrom(const FetchDataRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchDataRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.FetchDataRequest";
  }
  protected:
  explicit FetchDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskIdFieldNumber = 1,
  };
  // string task_id = 1;
  void clear_task_id();
  const std::string& task_id() const;
  void set_task_id(const std::string& value);
  void set_task_id(std::string&& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  std::string* mutable_task_id();
  std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_task_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_task_id(
      std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // @@protoc_insertion_point(class_scope:control.FetchDataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// -------------------------------------------------------------------

class FetchDataResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.FetchDataResponse) */ {
 public:
  inline FetchDataResponse() : FetchDataResponse(nullptr) {};
  virtual ~FetchDataResponse();

  FetchDataResponse(const FetchDataResponse& from);
  FetchDataResponse(FetchDataResponse&& from) noexcept
    : FetchDataResponse() {
    *this = ::std::move(from);
  }

  inline FetchDataResponse& operator=(const FetchDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchDataResponse& operator=(FetchDataResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchDataResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchDataResponse* internal_default_instance() {
    return reinterpret_cast<const FetchDataResponse*>(
               &_FetchDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FetchDataResponse& a, FetchDataResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchDataResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchDataResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchDataResponse* New() const final {
    return CreateMaybeMessage<FetchDataResponse>(nullptr);
  }

  FetchDataResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchDataResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchDataResponse& from);
  void MergeFrom(const FetchDataResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchDataResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.FetchDataResponse";
  }
  protected:
  explicit FetchDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCosKeyFieldNumber = 2,
    kErrorMessageFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // string cos_key = 2;
  void clear_cos_key();
  const std::string& cos_key() const;
  void set_cos_key(const std::string& value);
  void set_cos_key(std::string&& value);
  void set_cos_key(const char* value);
  void set_cos_key(const char* value, size_t size);
  std::string* mutable_cos_key();
  std::string* release_cos_key();
  void set_allocated_cos_key(std::string* cos_key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_cos_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_cos_key(
      std::string* cos_key);
  private:
  const std::string& _internal_cos_key() const;
  void _internal_set_cos_key(const std::string& value);
  std::string* _internal_mutable_cos_key();
  public:

  // string error_message = 3;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:control.FetchDataResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cos_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// -------------------------------------------------------------------

class StatAgentRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.StatAgentRequest) */ {
 public:
  inline StatAgentRequest() : StatAgentRequest(nullptr) {};
  virtual ~StatAgentRequest();

  StatAgentRequest(const StatAgentRequest& from);
  StatAgentRequest(StatAgentRequest&& from) noexcept
    : StatAgentRequest() {
    *this = ::std::move(from);
  }

  inline StatAgentRequest& operator=(const StatAgentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatAgentRequest& operator=(StatAgentRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StatAgentRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatAgentRequest* internal_default_instance() {
    return reinterpret_cast<const StatAgentRequest*>(
               &_StatAgentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StatAgentRequest& a, StatAgentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StatAgentRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatAgentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StatAgentRequest* New() const final {
    return CreateMaybeMessage<StatAgentRequest>(nullptr);
  }

  StatAgentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StatAgentRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StatAgentRequest& from);
  void MergeFrom(const StatAgentRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatAgentRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.StatAgentRequest";
  }
  protected:
  explicit StatAgentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpAddrFieldNumber = 1,
  };
  // string ip_addr = 1;
  void clear_ip_addr();
  const std::string& ip_addr() const;
  void set_ip_addr(const std::string& value);
  void set_ip_addr(std::string&& value);
  void set_ip_addr(const char* value);
  void set_ip_addr(const char* value, size_t size);
  std::string* mutable_ip_addr();
  std::string* release_ip_addr();
  void set_allocated_ip_addr(std::string* ip_addr);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ip_addr();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ip_addr(
      std::string* ip_addr);
  private:
  const std::string& _internal_ip_addr() const;
  void _internal_set_ip_addr(const std::string& value);
  std::string* _internal_mutable_ip_addr();
  public:

  // @@protoc_insertion_point(class_scope:control.StatAgentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_addr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// -------------------------------------------------------------------

class StatAgentResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:control.StatAgentResponse) */ {
 public:
  inline StatAgentResponse() : StatAgentResponse(nullptr) {};
  virtual ~StatAgentResponse();

  StatAgentResponse(const StatAgentResponse& from);
  StatAgentResponse(StatAgentResponse&& from) noexcept
    : StatAgentResponse() {
    *this = ::std::move(from);
  }

  inline StatAgentResponse& operator=(const StatAgentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatAgentResponse& operator=(StatAgentResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StatAgentResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatAgentResponse* internal_default_instance() {
    return reinterpret_cast<const StatAgentResponse*>(
               &_StatAgentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(StatAgentResponse& a, StatAgentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StatAgentResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatAgentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StatAgentResponse* New() const final {
    return CreateMaybeMessage<StatAgentResponse>(nullptr);
  }

  StatAgentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StatAgentResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StatAgentResponse& from);
  void MergeFrom(const StatAgentResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatAgentResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "control.StatAgentResponse";
  }
  protected:
  explicit StatAgentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLastHeartbeatFieldNumber = 4,
    kOnlineFieldNumber = 1,
    kCpuPercentFieldNumber = 2,
    kRssKbFieldNumber = 3,
  };
  // string last_heartbeat = 4;
  void clear_last_heartbeat();
  const std::string& last_heartbeat() const;
  void set_last_heartbeat(const std::string& value);
  void set_last_heartbeat(std::string&& value);
  void set_last_heartbeat(const char* value);
  void set_last_heartbeat(const char* value, size_t size);
  std::string* mutable_last_heartbeat();
  std::string* release_last_heartbeat();
  void set_allocated_last_heartbeat(std::string* last_heartbeat);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_last_heartbeat();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_last_heartbeat(
      std::string* last_heartbeat);
  private:
  const std::string& _internal_last_heartbeat() const;
  void _internal_set_last_heartbeat(const std::string& value);
  std::string* _internal_mutable_last_heartbeat();
  public:

  // bool online = 1;
  void clear_online();
  bool online() const;
  void set_online(bool value);
  private:
  bool _internal_online() const;
  void _internal_set_online(bool value);
  public:

  // float cpu_percent = 2;
  void clear_cpu_percent();
  float cpu_percent() const;
  void set_cpu_percent(float value);
  private:
  float _internal_cpu_percent() const;
  void _internal_set_cpu_percent(float value);
  public:

  // uint64 rss_kb = 3;
  void clear_rss_kb();
  ::PROTOBUF_NAMESPACE_ID::uint64 rss_kb() const;
  void set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_rss_kb() const;
  void _internal_set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:control.StatAgentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr last_heartbeat_;
  bool online_;
  float cpu_percent_;
  ::PROTOBUF_NAMESPACE_ID::uint64 rss_kb_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateTaskRequest

// string target_ip = 1;
inline void CreateTaskRequest::clear_target_ip() {
  target_ip_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreateTaskRequest::target_ip() const {
  // @@protoc_insertion_point(field_get:control.CreateTaskRequest.target_ip)
  return _internal_target_ip();
}
inline void CreateTaskRequest::set_target_ip(const std::string& value) {
  _internal_set_target_ip(value);
  // @@protoc_insertion_point(field_set:control.CreateTaskRequest.target_ip)
}
inline std::string* CreateTaskRequest::mutable_target_ip() {
  // @@protoc_insertion_point(field_mutable:control.CreateTaskRequest.target_ip)
  return _internal_mutable_target_ip();
}
inline const std::string& CreateTaskRequest::_internal_target_ip() const {
  return target_ip_.Get();
}
inline void CreateTaskRequest::_internal_set_target_ip(const std::string& value) {
  
  target_ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreateTaskRequest::set_target_ip(std::string&& value) {
  
  target_ip_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.CreateTaskRequest.target_ip)
}
inline void CreateTaskRequest::set_target_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  target_ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.CreateTaskRequest.target_ip)
}
inline void CreateTaskRequest::set_target_ip(const char* value,
    size_t size) {
  
  target_ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.CreateTaskRequest.target_ip)
}
inline std::string* CreateTaskRequest::_internal_mutable_target_ip() {
  
  return target_ip_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreateTaskRequest::release_target_ip() {
  // @@protoc_insertion_point(field_release:control.CreateTaskRequest.target_ip)
  return target_ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreateTaskRequest::set_allocated_target_ip(std::string* target_ip) {
  if (target_ip != nullptr) {
    
  } else {
    
  }
  target_ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), target_ip,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.CreateTaskRequest.target_ip)
}
inline std::string* CreateTaskRequest::unsafe_arena_release_target_ip() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.CreateTaskRequest.target_ip)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return target_ip_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreateTaskRequest::unsafe_arena_set_allocated_target_ip(
    std::string* target_ip) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (target_ip != nullptr) {
    
  } else {
    
  }
  target_ip_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      target_ip, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.CreateTaskRequest.target_ip)
}

// string service = 2;
inline void CreateTaskRequest::clear_service() {
  service_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreateTaskRequest::service() const {
  // @@protoc_insertion_point(field_get:control.CreateTaskRequest.service)
  return _internal_service();
}
inline void CreateTaskRequest::set_service(const std::string& value) {
  _internal_set_service(value);
  // @@protoc_insertion_point(field_set:control.CreateTaskRequest.service)
}
inline std::string* CreateTaskRequest::mutable_service() {
  // @@protoc_insertion_point(field_mutable:control.CreateTaskRequest.service)
  return _internal_mutable_service();
}
inline const std::string& CreateTaskRequest::_internal_service() const {
  return service_.Get();
}
inline void CreateTaskRequest::_internal_set_service(const std::string& value) {
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreateTaskRequest::set_service(std::string&& value) {
  
  service_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.CreateTaskRequest.service)
}
inline void CreateTaskRequest::set_service(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.CreateTaskRequest.service)
}
inline void CreateTaskRequest::set_service(const char* value,
    size_t size) {
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.CreateTaskRequest.service)
}
inline std::string* CreateTaskRequest::_internal_mutable_service() {
  
  return service_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreateTaskRequest::release_service() {
  // @@protoc_insertion_point(field_release:control.CreateTaskRequest.service)
  return service_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreateTaskRequest::set_allocated_service(std::string* service) {
  if (service != nullptr) {
    
  } else {
    
  }
  service_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.CreateTaskRequest.service)
}
inline std::string* CreateTaskRequest::unsafe_arena_release_service() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.CreateTaskRequest.service)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return service_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreateTaskRequest::unsafe_arena_set_allocated_service(
    std::string* service) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (service != nullptr) {
    
  } else {
    
  }
  service_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      service, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.CreateTaskRequest.service)
}

// .hotmethod.TaskDesc task_desc = 3;
inline bool CreateTaskRequest::_internal_has_task_desc() const {
  return this != internal_default_instance() && task_desc_ != nullptr;
}
inline bool CreateTaskRequest::has_task_desc() const {
  return _internal_has_task_desc();
}
inline const ::hotmethod::TaskDesc& CreateTaskRequest::_internal_task_desc() const {
  const ::hotmethod::TaskDesc* p = task_desc_;
  return p != nullptr ? *p : *reinterpret_cast<const ::hotmethod::TaskDesc*>(
      &::hotmethod::_TaskDesc_default_instance_);
}
inline const ::hotmethod::TaskDesc& CreateTaskRequest::task_desc() const {
  // @@protoc_insertion_point(field_get:control.CreateTaskRequest.task_desc)
  return _internal_task_desc();
}
inline void CreateTaskRequest::unsafe_arena_set_allocated_task_desc(
    ::hotmethod::TaskDesc* task_desc) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(task_desc_);
  }
  task_desc_ = task_desc;
  if (task_desc) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.CreateTaskRequest.task_desc)
}
inline ::hotmethod::TaskDesc* CreateTaskRequest::release_task_desc() {
  auto temp = unsafe_arena_release_task_desc();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::hotmethod::TaskDesc* CreateTaskRequest::unsafe_arena_release_task_desc() {
  // @@protoc_insertion_point(field_release:control.CreateTaskRequest.task_desc)
  
  ::hotmethod::TaskDesc* temp = task_desc_;
  task_desc_ = nullptr;
  return temp;
}
inline ::hotmethod::TaskDesc* CreateTaskRequest::_internal_mutable_task_desc() {
  
  if (task_desc_ == nullptr) {
    auto* p = CreateMaybeMessage<::hotmethod::TaskDesc>(GetArena());
    task_desc_ = p;
  }
  return task_desc_;
}
inline ::hotmethod::TaskDesc* CreateTaskRequest::mutable_task_desc() {
  // @@protoc_insertion_point(field_mutable:control.CreateTaskRequest.task_desc)
  return _internal_mutable_task_desc();
}
inline void CreateTaskRequest::set_allocated_task_desc(::hotmethod::TaskDesc* task_desc) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(task_desc_);
  }
  if (task_desc) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(task_desc)->GetArena();
    if (message_arena != submessage_arena) {
      task_desc = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, task_desc, submessage_arena);
    }
    
  } else {
    
  }
  task_desc_ = task_desc;
  // @@protoc_insertion_point(field_set_allocated:control.CreateTaskRequest.task_desc)
}

// -------------------------------------------------------------------

// CreateTaskResponse

// bool success = 1;
inline void CreateTaskResponse::clear_success() {
  success_ = false;
}
inline bool CreateTaskResponse::_internal_success() const {
  return success_;
}
inline bool CreateTaskResponse::success() const {
  // @@protoc_insertion_point(field_get:control.CreateTaskResponse.success)
  return _internal_success();
}
inline void CreateTaskResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void CreateTaskResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:control.CreateTaskResponse.success)
}

// string message = 2;
inline void CreateTaskResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreateTaskResponse::message() const {
  // @@protoc_insertion_point(field_get:control.CreateTaskResponse.message)
  return _internal_message();
}
inline void CreateTaskResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:control.CreateTaskResponse.message)
}
inline std::string* CreateTaskResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:control.CreateTaskResponse.message)
  return _internal_mutable_message();
}
inline const std::string& CreateTaskResponse::_internal_message() const {
  return message_.Get();
}
inline void CreateTaskResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreateTaskResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.CreateTaskResponse.message)
}
inline void CreateTaskResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.CreateTaskResponse.message)
}
inline void CreateTaskResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.CreateTaskResponse.message)
}
inline std::string* CreateTaskResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreateTaskResponse::release_message() {
  // @@protoc_insertion_point(field_release:control.CreateTaskResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreateTaskResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.CreateTaskResponse.message)
}
inline std::string* CreateTaskResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.CreateTaskResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreateTaskResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.CreateTaskResponse.message)
}

// -------------------------------------------------------------------

// FetchDataRequest

// string task_id = 1;
inline void FetchDataRequest::clear_task_id() {
  task_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FetchDataRequest::task_id() const {
  // @@protoc_insertion_point(field_get:control.FetchDataRequest.task_id)
  return _internal_task_id();
}
inline void FetchDataRequest::set_task_id(const std::string& value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:control.FetchDataRequest.task_id)
}
inline std::string* FetchDataRequest::mutable_task_id() {
  // @@protoc_insertion_point(field_mutable:control.FetchDataRequest.task_id)
  return _internal_mutable_task_id();
}
inline const std::string& FetchDataRequest::_internal_task_id() const {
  return task_id_.Get();
}
inline void FetchDataRequest::_internal_set_task_id(const std::string& value) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FetchDataRequest::set_task_id(std::string&& value) {
  
  task_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.FetchDataRequest.task_id)
}
inline void FetchDataRequest::set_task_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.FetchDataRequest.task_id)
}
inline void FetchDataRequest::set_task_id(const char* value,
    size_t size) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.FetchDataRequest.task_id)
}
inline std::string* FetchDataRequest::_internal_mutable_task_id() {
  
  return task_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FetchDataRequest::release_task_id() {
  // @@protoc_insertion_point(field_release:control.FetchDataRequest.task_id)
  return task_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FetchDataRequest::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.FetchDataRequest.task_id)
}
inline std::string* FetchDataRequest::unsafe_arena_release_task_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.FetchDataRequest.task_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return task_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FetchDataRequest::unsafe_arena_set_allocated_task_id(
    std::string* task_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      task_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.FetchDataRequest.task_id)
}

// -------------------------------------------------------------------

// FetchDataResponse

// bool success = 1;
inline void FetchDataResponse::clear_success() {
  success_ = false;
}
inline bool FetchDataResponse::_internal_success() const {
  return success_;
}
inline bool FetchDataResponse::success() const {
  // @@protoc_insertion_point(field_get:control.FetchDataResponse.success)
  return _internal_success();
}
inline void FetchDataResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void FetchDataResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:control.FetchDataResponse.success)
}

// string cos_key = 2;
inline void FetchDataResponse::clear_cos_key() {
  cos_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FetchDataResponse::cos_key() const {
  // @@protoc_insertion_point(field_get:control.FetchDataResponse.cos_key)
  return _internal_cos_key();
}
inline void FetchDataResponse::set_cos_key(const std::string& value) {
  _internal_set_cos_key(value);
  // @@protoc_insertion_point(field_set:control.FetchDataResponse.cos_key)
}
inline std::string* FetchDataResponse::mutable_cos_key() {
  // @@protoc_insertion_point(field_mutable:control.FetchDataResponse.cos_key)
  return _internal_mutable_cos_key();
}
inline const std::string& FetchDataResponse::_internal_cos_key() const {
  return cos_key_.Get();
}
inline void FetchDataResponse::_internal_set_cos_key(const std::string& value) {
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FetchDataResponse::set_cos_key(std::string&& value) {
  
  cos_key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.FetchDataResponse.cos_key)
}
inline void FetchDataResponse::set_cos_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.FetchDataResponse.cos_key)
}
inline void FetchDataResponse::set_cos_key(const char* value,
    size_t size) {
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.FetchDataResponse.cos_key)
}
inline std::string* FetchDataResponse::_internal_mutable_cos_key() {
  
  return cos_key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FetchDataResponse::release_cos_key() {
  // @@protoc_insertion_point(field_release:control.FetchDataResponse.cos_key)
  return cos_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FetchDataResponse::set_allocated_cos_key(std::string* cos_key) {
  if (cos_key != nullptr) {
    
  } else {
    
  }
  cos_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cos_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.FetchDataResponse.cos_key)
}
inline std::string* FetchDataResponse::unsafe_arena_release_cos_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.FetchDataResponse.cos_key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return cos_key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FetchDataResponse::unsafe_arena_set_allocated_cos_key(
    std::string* cos_key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (cos_key != nullptr) {
    
  } else {
    
  }
  cos_key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      cos_key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.FetchDataResponse.cos_key)
}

// string error_message = 3;
inline void FetchDataResponse::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FetchDataResponse::error_message() const {
  // @@protoc_insertion_point(field_get:control.FetchDataResponse.error_message)
  return _internal_error_message();
}
inline void FetchDataResponse::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:control.FetchDataResponse.error_message)
}
inline std::string* FetchDataResponse::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:control.FetchDataResponse.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& FetchDataResponse::_internal_error_message() const {
  return error_message_.Get();
}
inline void FetchDataResponse::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FetchDataResponse::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.FetchDataResponse.error_message)
}
inline void FetchDataResponse::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.FetchDataResponse.error_message)
}
inline void FetchDataResponse::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.FetchDataResponse.error_message)
}
inline std::string* FetchDataResponse::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FetchDataResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:control.FetchDataResponse.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FetchDataResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.FetchDataResponse.error_message)
}
inline std::string* FetchDataResponse::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.FetchDataResponse.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FetchDataResponse::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.FetchDataResponse.error_message)
}

// -------------------------------------------------------------------

// StatAgentRequest

// string ip_addr = 1;
inline void StatAgentRequest::clear_ip_addr() {
  ip_addr_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StatAgentRequest::ip_addr() const {
  // @@protoc_insertion_point(field_get:control.StatAgentRequest.ip_addr)
  return _internal_ip_addr();
}
inline void StatAgentRequest::set_ip_addr(const std::string& value) {
  _internal_set_ip_addr(value);
  // @@protoc_insertion_point(field_set:control.StatAgentRequest.ip_addr)
}
inline std::string* StatAgentRequest::mutable_ip_addr() {
  // @@protoc_insertion_point(field_mutable:control.StatAgentRequest.ip_addr)
  return _internal_mutable_ip_addr();
}
inline const std::string& StatAgentRequest::_internal_ip_addr() const {
  return ip_addr_.Get();
}
inline void StatAgentRequest::_internal_set_ip_addr(const std::string& value) {
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StatAgentRequest::set_ip_addr(std::string&& value) {
  
  ip_addr_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.StatAgentRequest.ip_addr)
}
inline void StatAgentRequest::set_ip_addr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.StatAgentRequest.ip_addr)
}
inline void StatAgentRequest::set_ip_addr(const char* value,
    size_t size) {
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.StatAgentRequest.ip_addr)
}
inline std::string* StatAgentRequest::_internal_mutable_ip_addr() {
  
  return ip_addr_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StatAgentRequest::release_ip_addr() {
  // @@protoc_insertion_point(field_release:control.StatAgentRequest.ip_addr)
  return ip_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StatAgentRequest::set_allocated_ip_addr(std::string* ip_addr) {
  if (ip_addr != nullptr) {
    
  } else {
    
  }
  ip_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip_addr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.StatAgentRequest.ip_addr)
}
inline std::string* StatAgentRequest::unsafe_arena_release_ip_addr() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.StatAgentRequest.ip_addr)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return ip_addr_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StatAgentRequest::unsafe_arena_set_allocated_ip_addr(
    std::string* ip_addr) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ip_addr != nullptr) {
    
  } else {
    
  }
  ip_addr_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ip_addr, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.StatAgentRequest.ip_addr)
}

// -------------------------------------------------------------------

// StatAgentResponse

// bool online = 1;
inline void StatAgentResponse::clear_online() {
  online_ = false;
}
inline bool StatAgentResponse::_internal_online() const {
  return online_;
}
inline bool StatAgentResponse::online() const {
  // @@protoc_insertion_point(field_get:control.StatAgentResponse.online)
  return _internal_online();
}
inline void StatAgentResponse::_internal_set_online(bool value) {
  
  online_ = value;
}
inline void StatAgentResponse::set_online(bool value) {
  _internal_set_online(value);
  // @@protoc_insertion_point(field_set:control.StatAgentResponse.online)
}

// float cpu_percent = 2;
inline void StatAgentResponse::clear_cpu_percent() {
  cpu_percent_ = 0;
}
inline float StatAgentResponse::_internal_cpu_percent() const {
  return cpu_percent_;
}
inline float StatAgentResponse::cpu_percent() const {
  // @@protoc_insertion_point(field_get:control.StatAgentResponse.cpu_percent)
  return _internal_cpu_percent();
}
inline void StatAgentResponse::_internal_set_cpu_percent(float value) {
  
  cpu_percent_ = value;
}
inline void StatAgentResponse::set_cpu_percent(float value) {
  _internal_set_cpu_percent(value);
  // @@protoc_insertion_point(field_set:control.StatAgentResponse.cpu_percent)
}

// uint64 rss_kb = 3;
inline void StatAgentResponse::clear_rss_kb() {
  rss_kb_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatAgentResponse::_internal_rss_kb() const {
  return rss_kb_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 StatAgentResponse::rss_kb() const {
  // @@protoc_insertion_point(field_get:control.StatAgentResponse.rss_kb)
  return _internal_rss_kb();
}
inline void StatAgentResponse::_internal_set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  rss_kb_ = value;
}
inline void StatAgentResponse::set_rss_kb(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_rss_kb(value);
  // @@protoc_insertion_point(field_set:control.StatAgentResponse.rss_kb)
}

// string last_heartbeat = 4;
inline void StatAgentResponse::clear_last_heartbeat() {
  last_heartbeat_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& StatAgentResponse::last_heartbeat() const {
  // @@protoc_insertion_point(field_get:control.StatAgentResponse.last_heartbeat)
  return _internal_last_heartbeat();
}
inline void StatAgentResponse::set_last_heartbeat(const std::string& value) {
  _internal_set_last_heartbeat(value);
  // @@protoc_insertion_point(field_set:control.StatAgentResponse.last_heartbeat)
}
inline std::string* StatAgentResponse::mutable_last_heartbeat() {
  // @@protoc_insertion_point(field_mutable:control.StatAgentResponse.last_heartbeat)
  return _internal_mutable_last_heartbeat();
}
inline const std::string& StatAgentResponse::_internal_last_heartbeat() const {
  return last_heartbeat_.Get();
}
inline void StatAgentResponse::_internal_set_last_heartbeat(const std::string& value) {
  
  last_heartbeat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void StatAgentResponse::set_last_heartbeat(std::string&& value) {
  
  last_heartbeat_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:control.StatAgentResponse.last_heartbeat)
}
inline void StatAgentResponse::set_last_heartbeat(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  last_heartbeat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:control.StatAgentResponse.last_heartbeat)
}
inline void StatAgentResponse::set_last_heartbeat(const char* value,
    size_t size) {
  
  last_heartbeat_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:control.StatAgentResponse.last_heartbeat)
}
inline std::string* StatAgentResponse::_internal_mutable_last_heartbeat() {
  
  return last_heartbeat_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* StatAgentResponse::release_last_heartbeat() {
  // @@protoc_insertion_point(field_release:control.StatAgentResponse.last_heartbeat)
  return last_heartbeat_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void StatAgentResponse::set_allocated_last_heartbeat(std::string* last_heartbeat) {
  if (last_heartbeat != nullptr) {
    
  } else {
    
  }
  last_heartbeat_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), last_heartbeat,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:control.StatAgentResponse.last_heartbeat)
}
inline std::string* StatAgentResponse::unsafe_arena_release_last_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:control.StatAgentResponse.last_heartbeat)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return last_heartbeat_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void StatAgentResponse::unsafe_arena_set_allocated_last_heartbeat(
    std::string* last_heartbeat) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (last_heartbeat != nullptr) {
    
  } else {
    
  }
  last_heartbeat_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      last_heartbeat, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:control.StatAgentResponse.last_heartbeat)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace control

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_2eproto
