// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_init_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_init_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_init_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_init_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_init_2eproto;
namespace init_svc {
class FetchConfigRequest;
class FetchConfigRequestDefaultTypeInternal;
extern FetchConfigRequestDefaultTypeInternal _FetchConfigRequest_default_instance_;
class FetchConfigResponse;
class FetchConfigResponseDefaultTypeInternal;
extern FetchConfigResponseDefaultTypeInternal _FetchConfigResponse_default_instance_;
class RegisterAgentRequest;
class RegisterAgentRequestDefaultTypeInternal;
extern RegisterAgentRequestDefaultTypeInternal _RegisterAgentRequest_default_instance_;
class RegisterAgentResponse;
class RegisterAgentResponseDefaultTypeInternal;
extern RegisterAgentResponseDefaultTypeInternal _RegisterAgentResponse_default_instance_;
}  // namespace init_svc
PROTOBUF_NAMESPACE_OPEN
template<> ::init_svc::FetchConfigRequest* Arena::CreateMaybeMessage<::init_svc::FetchConfigRequest>(Arena*);
template<> ::init_svc::FetchConfigResponse* Arena::CreateMaybeMessage<::init_svc::FetchConfigResponse>(Arena*);
template<> ::init_svc::RegisterAgentRequest* Arena::CreateMaybeMessage<::init_svc::RegisterAgentRequest>(Arena*);
template<> ::init_svc::RegisterAgentResponse* Arena::CreateMaybeMessage<::init_svc::RegisterAgentResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace init_svc {

// ===================================================================

class RegisterAgentRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:init_svc.RegisterAgentRequest) */ {
 public:
  inline RegisterAgentRequest() : RegisterAgentRequest(nullptr) {};
  virtual ~RegisterAgentRequest();

  RegisterAgentRequest(const RegisterAgentRequest& from);
  RegisterAgentRequest(RegisterAgentRequest&& from) noexcept
    : RegisterAgentRequest() {
    *this = ::std::move(from);
  }

  inline RegisterAgentRequest& operator=(const RegisterAgentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterAgentRequest& operator=(RegisterAgentRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterAgentRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterAgentRequest* internal_default_instance() {
    return reinterpret_cast<const RegisterAgentRequest*>(
               &_RegisterAgentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegisterAgentRequest& a, RegisterAgentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterAgentRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterAgentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterAgentRequest* New() const final {
    return CreateMaybeMessage<RegisterAgentRequest>(nullptr);
  }

  RegisterAgentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterAgentRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterAgentRequest& from);
  void MergeFrom(const RegisterAgentRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterAgentRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "init_svc.RegisterAgentRequest";
  }
  protected:
  explicit RegisterAgentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_init_2eproto);
    return ::descriptor_table_init_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostNameFieldNumber = 1,
    kIpAddrFieldNumber = 2,
    kUidFieldNumber = 3,
    kAgentVersionFieldNumber = 4,
    kEnvironmentFieldNumber = 5,
  };
  // string host_name = 1;
  void clear_host_name();
  const std::string& host_name() const;
  void set_host_name(const std::string& value);
  void set_host_name(std::string&& value);
  void set_host_name(const char* value);
  void set_host_name(const char* value, size_t size);
  std::string* mutable_host_name();
  std::string* release_host_name();
  void set_allocated_host_name(std::string* host_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_host_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_host_name(
      std::string* host_name);
  private:
  const std::string& _internal_host_name() const;
  void _internal_set_host_name(const std::string& value);
  std::string* _internal_mutable_host_name();
  public:

  // string ip_addr = 2;
  void clear_ip_addr();
  const std::string& ip_addr() const;
  void set_ip_addr(const std::string& value);
  void set_ip_addr(std::string&& value);
  void set_ip_addr(const char* value);
  void set_ip_addr(const char* value, size_t size);
  std::string* mutable_ip_addr();
  std::string* release_ip_addr();
  void set_allocated_ip_addr(std::string* ip_addr);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ip_addr();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ip_addr(
      std::string* ip_addr);
  private:
  const std::string& _internal_ip_addr() const;
  void _internal_set_ip_addr(const std::string& value);
  std::string* _internal_mutable_ip_addr();
  public:

  // string uid = 3;
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uid(
      std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // string agent_version = 4;
  void clear_agent_version();
  const std::string& agent_version() const;
  void set_agent_version(const std::string& value);
  void set_agent_version(std::string&& value);
  void set_agent_version(const char* value);
  void set_agent_version(const char* value, size_t size);
  std::string* mutable_agent_version();
  std::string* release_agent_version();
  void set_allocated_agent_version(std::string* agent_version);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_agent_version();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_agent_version(
      std::string* agent_version);
  private:
  const std::string& _internal_agent_version() const;
  void _internal_set_agent_version(const std::string& value);
  std::string* _internal_mutable_agent_version();
  public:

  // string environment = 5;
  void clear_environment();
  const std::string& environment() const;
  void set_environment(const std::string& value);
  void set_environment(std::string&& value);
  void set_environment(const char* value);
  void set_environment(const char* value, size_t size);
  std::string* mutable_environment();
  std::string* release_environment();
  void set_allocated_environment(std::string* environment);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_environment();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_environment(
      std::string* environment);
  private:
  const std::string& _internal_environment() const;
  void _internal_set_environment(const std::string& value);
  std::string* _internal_mutable_environment();
  public:

  // @@protoc_insertion_point(class_scope:init_svc.RegisterAgentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_addr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr agent_version_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr environment_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_init_2eproto;
};
// -------------------------------------------------------------------

class RegisterAgentResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:init_svc.RegisterAgentResponse) */ {
 public:
  inline RegisterAgentResponse() : RegisterAgentResponse(nullptr) {};
  virtual ~RegisterAgentResponse();

  RegisterAgentResponse(const RegisterAgentResponse& from);
  RegisterAgentResponse(RegisterAgentResponse&& from) noexcept
    : RegisterAgentResponse() {
    *this = ::std::move(from);
  }

  inline RegisterAgentResponse& operator=(const RegisterAgentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterAgentResponse& operator=(RegisterAgentResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterAgentResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterAgentResponse* internal_default_instance() {
    return reinterpret_cast<const RegisterAgentResponse*>(
               &_RegisterAgentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RegisterAgentResponse& a, RegisterAgentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterAgentResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterAgentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterAgentResponse* New() const final {
    return CreateMaybeMessage<RegisterAgentResponse>(nullptr);
  }

  RegisterAgentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterAgentResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterAgentResponse& from);
  void MergeFrom(const RegisterAgentResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterAgentResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "init_svc.RegisterAgentResponse";
  }
  protected:
  explicit RegisterAgentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_init_2eproto);
    return ::descriptor_table_init_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:init_svc.RegisterAgentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_init_2eproto;
};
// -------------------------------------------------------------------

class FetchConfigRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:init_svc.FetchConfigRequest) */ {
 public:
  inline FetchConfigRequest() : FetchConfigRequest(nullptr) {};
  virtual ~FetchConfigRequest();

  FetchConfigRequest(const FetchConfigRequest& from);
  FetchConfigRequest(FetchConfigRequest&& from) noexcept
    : FetchConfigRequest() {
    *this = ::std::move(from);
  }

  inline FetchConfigRequest& operator=(const FetchConfigRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchConfigRequest& operator=(FetchConfigRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchConfigRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchConfigRequest* internal_default_instance() {
    return reinterpret_cast<const FetchConfigRequest*>(
               &_FetchConfigRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FetchConfigRequest& a, FetchConfigRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchConfigRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchConfigRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchConfigRequest* New() const final {
    return CreateMaybeMessage<FetchConfigRequest>(nullptr);
  }

  FetchConfigRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchConfigRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchConfigRequest& from);
  void MergeFrom(const FetchConfigRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchConfigRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "init_svc.FetchConfigRequest";
  }
  protected:
  explicit FetchConfigRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_init_2eproto);
    return ::descriptor_table_init_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUidFieldNumber = 1,
  };
  // string uid = 1;
  void clear_uid();
  const std::string& uid() const;
  void set_uid(const std::string& value);
  void set_uid(std::string&& value);
  void set_uid(const char* value);
  void set_uid(const char* value, size_t size);
  std::string* mutable_uid();
  std::string* release_uid();
  void set_allocated_uid(std::string* uid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uid(
      std::string* uid);
  private:
  const std::string& _internal_uid() const;
  void _internal_set_uid(const std::string& value);
  std::string* _internal_mutable_uid();
  public:

  // @@protoc_insertion_point(class_scope:init_svc.FetchConfigRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_init_2eproto;
};
// -------------------------------------------------------------------

class FetchConfigResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:init_svc.FetchConfigResponse) */ {
 public:
  inline FetchConfigResponse() : FetchConfigResponse(nullptr) {};
  virtual ~FetchConfigResponse();

  FetchConfigResponse(const FetchConfigResponse& from);
  FetchConfigResponse(FetchConfigResponse&& from) noexcept
    : FetchConfigResponse() {
    *this = ::std::move(from);
  }

  inline FetchConfigResponse& operator=(const FetchConfigResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FetchConfigResponse& operator=(FetchConfigResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FetchConfigResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FetchConfigResponse* internal_default_instance() {
    return reinterpret_cast<const FetchConfigResponse*>(
               &_FetchConfigResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FetchConfigResponse& a, FetchConfigResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FetchConfigResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FetchConfigResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FetchConfigResponse* New() const final {
    return CreateMaybeMessage<FetchConfigResponse>(nullptr);
  }

  FetchConfigResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FetchConfigResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FetchConfigResponse& from);
  void MergeFrom(const FetchConfigResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FetchConfigResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "init_svc.FetchConfigResponse";
  }
  protected:
  explicit FetchConfigResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_init_2eproto);
    return ::descriptor_table_init_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 3,
    kCosConfigFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 3;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .drop.CosConfig cos_config = 2;
  bool has_cos_config() const;
  private:
  bool _internal_has_cos_config() const;
  public:
  void clear_cos_config();
  const ::drop::CosConfig& cos_config() const;
  ::drop::CosConfig* release_cos_config();
  ::drop::CosConfig* mutable_cos_config();
  void set_allocated_cos_config(::drop::CosConfig* cos_config);
  private:
  const ::drop::CosConfig& _internal_cos_config() const;
  ::drop::CosConfig* _internal_mutable_cos_config();
  public:
  void unsafe_arena_set_allocated_cos_config(
      ::drop::CosConfig* cos_config);
  ::drop::CosConfig* unsafe_arena_release_cos_config();

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:init_svc.FetchConfigResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::drop::CosConfig* cos_config_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_init_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterAgentRequest

// string host_name = 1;
inline void RegisterAgentRequest::clear_host_name() {
  host_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentRequest::host_name() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentRequest.host_name)
  return _internal_host_name();
}
inline void RegisterAgentRequest::set_host_name(const std::string& value) {
  _internal_set_host_name(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentRequest.host_name)
}
inline std::string* RegisterAgentRequest::mutable_host_name() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentRequest.host_name)
  return _internal_mutable_host_name();
}
inline const std::string& RegisterAgentRequest::_internal_host_name() const {
  return host_name_.Get();
}
inline void RegisterAgentRequest::_internal_set_host_name(const std::string& value) {
  
  host_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentRequest::set_host_name(std::string&& value) {
  
  host_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentRequest.host_name)
}
inline void RegisterAgentRequest::set_host_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  host_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentRequest.host_name)
}
inline void RegisterAgentRequest::set_host_name(const char* value,
    size_t size) {
  
  host_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentRequest.host_name)
}
inline std::string* RegisterAgentRequest::_internal_mutable_host_name() {
  
  return host_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentRequest::release_host_name() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentRequest.host_name)
  return host_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentRequest::set_allocated_host_name(std::string* host_name) {
  if (host_name != nullptr) {
    
  } else {
    
  }
  host_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), host_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentRequest.host_name)
}
inline std::string* RegisterAgentRequest::unsafe_arena_release_host_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentRequest.host_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return host_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentRequest::unsafe_arena_set_allocated_host_name(
    std::string* host_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (host_name != nullptr) {
    
  } else {
    
  }
  host_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      host_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentRequest.host_name)
}

// string ip_addr = 2;
inline void RegisterAgentRequest::clear_ip_addr() {
  ip_addr_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentRequest::ip_addr() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentRequest.ip_addr)
  return _internal_ip_addr();
}
inline void RegisterAgentRequest::set_ip_addr(const std::string& value) {
  _internal_set_ip_addr(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentRequest.ip_addr)
}
inline std::string* RegisterAgentRequest::mutable_ip_addr() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentRequest.ip_addr)
  return _internal_mutable_ip_addr();
}
inline const std::string& RegisterAgentRequest::_internal_ip_addr() const {
  return ip_addr_.Get();
}
inline void RegisterAgentRequest::_internal_set_ip_addr(const std::string& value) {
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentRequest::set_ip_addr(std::string&& value) {
  
  ip_addr_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentRequest.ip_addr)
}
inline void RegisterAgentRequest::set_ip_addr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentRequest.ip_addr)
}
inline void RegisterAgentRequest::set_ip_addr(const char* value,
    size_t size) {
  
  ip_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentRequest.ip_addr)
}
inline std::string* RegisterAgentRequest::_internal_mutable_ip_addr() {
  
  return ip_addr_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentRequest::release_ip_addr() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentRequest.ip_addr)
  return ip_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentRequest::set_allocated_ip_addr(std::string* ip_addr) {
  if (ip_addr != nullptr) {
    
  } else {
    
  }
  ip_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip_addr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentRequest.ip_addr)
}
inline std::string* RegisterAgentRequest::unsafe_arena_release_ip_addr() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentRequest.ip_addr)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return ip_addr_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentRequest::unsafe_arena_set_allocated_ip_addr(
    std::string* ip_addr) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ip_addr != nullptr) {
    
  } else {
    
  }
  ip_addr_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ip_addr, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentRequest.ip_addr)
}

// string uid = 3;
inline void RegisterAgentRequest::clear_uid() {
  uid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentRequest::uid() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentRequest.uid)
  return _internal_uid();
}
inline void RegisterAgentRequest::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentRequest.uid)
}
inline std::string* RegisterAgentRequest::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentRequest.uid)
  return _internal_mutable_uid();
}
inline const std::string& RegisterAgentRequest::_internal_uid() const {
  return uid_.Get();
}
inline void RegisterAgentRequest::_internal_set_uid(const std::string& value) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentRequest::set_uid(std::string&& value) {
  
  uid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentRequest.uid)
}
inline void RegisterAgentRequest::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentRequest.uid)
}
inline void RegisterAgentRequest::set_uid(const char* value,
    size_t size) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentRequest.uid)
}
inline std::string* RegisterAgentRequest::_internal_mutable_uid() {
  
  return uid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentRequest::release_uid() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentRequest.uid)
  return uid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentRequest::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentRequest.uid)
}
inline std::string* RegisterAgentRequest::unsafe_arena_release_uid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentRequest.uid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentRequest::unsafe_arena_set_allocated_uid(
    std::string* uid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentRequest.uid)
}

// string agent_version = 4;
inline void RegisterAgentRequest::clear_agent_version() {
  agent_version_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentRequest::agent_version() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentRequest.agent_version)
  return _internal_agent_version();
}
inline void RegisterAgentRequest::set_agent_version(const std::string& value) {
  _internal_set_agent_version(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentRequest.agent_version)
}
inline std::string* RegisterAgentRequest::mutable_agent_version() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentRequest.agent_version)
  return _internal_mutable_agent_version();
}
inline const std::string& RegisterAgentRequest::_internal_agent_version() const {
  return agent_version_.Get();
}
inline void RegisterAgentRequest::_internal_set_agent_version(const std::string& value) {
  
  agent_version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentRequest::set_agent_version(std::string&& value) {
  
  agent_version_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentRequest.agent_version)
}
inline void RegisterAgentRequest::set_agent_version(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  agent_version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentRequest.agent_version)
}
inline void RegisterAgentRequest::set_agent_version(const char* value,
    size_t size) {
  
  agent_version_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentRequest.agent_version)
}
inline std::string* RegisterAgentRequest::_internal_mutable_agent_version() {
  
  return agent_version_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentRequest::release_agent_version() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentRequest.agent_version)
  return agent_version_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentRequest::set_allocated_agent_version(std::string* agent_version) {
  if (agent_version != nullptr) {
    
  } else {
    
  }
  agent_version_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), agent_version,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentRequest.agent_version)
}
inline std::string* RegisterAgentRequest::unsafe_arena_release_agent_version() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentRequest.agent_version)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return agent_version_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentRequest::unsafe_arena_set_allocated_agent_version(
    std::string* agent_version) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (agent_version != nullptr) {
    
  } else {
    
  }
  agent_version_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      agent_version, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentRequest.agent_version)
}

// string environment = 5;
inline void RegisterAgentRequest::clear_environment() {
  environment_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentRequest::environment() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentRequest.environment)
  return _internal_environment();
}
inline void RegisterAgentRequest::set_environment(const std::string& value) {
  _internal_set_environment(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentRequest.environment)
}
inline std::string* RegisterAgentRequest::mutable_environment() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentRequest.environment)
  return _internal_mutable_environment();
}
inline const std::string& RegisterAgentRequest::_internal_environment() const {
  return environment_.Get();
}
inline void RegisterAgentRequest::_internal_set_environment(const std::string& value) {
  
  environment_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentRequest::set_environment(std::string&& value) {
  
  environment_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentRequest.environment)
}
inline void RegisterAgentRequest::set_environment(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  environment_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentRequest.environment)
}
inline void RegisterAgentRequest::set_environment(const char* value,
    size_t size) {
  
  environment_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentRequest.environment)
}
inline std::string* RegisterAgentRequest::_internal_mutable_environment() {
  
  return environment_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentRequest::release_environment() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentRequest.environment)
  return environment_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentRequest::set_allocated_environment(std::string* environment) {
  if (environment != nullptr) {
    
  } else {
    
  }
  environment_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), environment,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentRequest.environment)
}
inline std::string* RegisterAgentRequest::unsafe_arena_release_environment() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentRequest.environment)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return environment_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentRequest::unsafe_arena_set_allocated_environment(
    std::string* environment) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (environment != nullptr) {
    
  } else {
    
  }
  environment_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      environment, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentRequest.environment)
}

// -------------------------------------------------------------------

// RegisterAgentResponse

// bool success = 1;
inline void RegisterAgentResponse::clear_success() {
  success_ = false;
}
inline bool RegisterAgentResponse::_internal_success() const {
  return success_;
}
inline bool RegisterAgentResponse::success() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentResponse.success)
  return _internal_success();
}
inline void RegisterAgentResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void RegisterAgentResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentResponse.success)
}

// string message = 2;
inline void RegisterAgentResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterAgentResponse::message() const {
  // @@protoc_insertion_point(field_get:init_svc.RegisterAgentResponse.message)
  return _internal_message();
}
inline void RegisterAgentResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:init_svc.RegisterAgentResponse.message)
}
inline std::string* RegisterAgentResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:init_svc.RegisterAgentResponse.message)
  return _internal_mutable_message();
}
inline const std::string& RegisterAgentResponse::_internal_message() const {
  return message_.Get();
}
inline void RegisterAgentResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterAgentResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.RegisterAgentResponse.message)
}
inline void RegisterAgentResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.RegisterAgentResponse.message)
}
inline void RegisterAgentResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.RegisterAgentResponse.message)
}
inline std::string* RegisterAgentResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterAgentResponse::release_message() {
  // @@protoc_insertion_point(field_release:init_svc.RegisterAgentResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterAgentResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.RegisterAgentResponse.message)
}
inline std::string* RegisterAgentResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.RegisterAgentResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterAgentResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.RegisterAgentResponse.message)
}

// -------------------------------------------------------------------

// FetchConfigRequest

// string uid = 1;
inline void FetchConfigRequest::clear_uid() {
  uid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FetchConfigRequest::uid() const {
  // @@protoc_insertion_point(field_get:init_svc.FetchConfigRequest.uid)
  return _internal_uid();
}
inline void FetchConfigRequest::set_uid(const std::string& value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:init_svc.FetchConfigRequest.uid)
}
inline std::string* FetchConfigRequest::mutable_uid() {
  // @@protoc_insertion_point(field_mutable:init_svc.FetchConfigRequest.uid)
  return _internal_mutable_uid();
}
inline const std::string& FetchConfigRequest::_internal_uid() const {
  return uid_.Get();
}
inline void FetchConfigRequest::_internal_set_uid(const std::string& value) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FetchConfigRequest::set_uid(std::string&& value) {
  
  uid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.FetchConfigRequest.uid)
}
inline void FetchConfigRequest::set_uid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.FetchConfigRequest.uid)
}
inline void FetchConfigRequest::set_uid(const char* value,
    size_t size) {
  
  uid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.FetchConfigRequest.uid)
}
inline std::string* FetchConfigRequest::_internal_mutable_uid() {
  
  return uid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FetchConfigRequest::release_uid() {
  // @@protoc_insertion_point(field_release:init_svc.FetchConfigRequest.uid)
  return uid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FetchConfigRequest::set_allocated_uid(std::string* uid) {
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.FetchConfigRequest.uid)
}
inline std::string* FetchConfigRequest::unsafe_arena_release_uid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.FetchConfigRequest.uid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FetchConfigRequest::unsafe_arena_set_allocated_uid(
    std::string* uid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uid != nullptr) {
    
  } else {
    
  }
  uid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.FetchConfigRequest.uid)
}

// -------------------------------------------------------------------

// FetchConfigResponse

// bool success = 1;
inline void FetchConfigResponse::clear_success() {
  success_ = false;
}
inline bool FetchConfigResponse::_internal_success() const {
  return success_;
}
inline bool FetchConfigResponse::success() const {
  // @@protoc_insertion_point(field_get:init_svc.FetchConfigResponse.success)
  return _internal_success();
}
inline void FetchConfigResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void FetchConfigResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:init_svc.FetchConfigResponse.success)
}

// .drop.CosConfig cos_config = 2;
inline bool FetchConfigResponse::_internal_has_cos_config() const {
  return this != internal_default_instance() && cos_config_ != nullptr;
}
inline bool FetchConfigResponse::has_cos_config() const {
  return _internal_has_cos_config();
}
inline const ::drop::CosConfig& FetchConfigResponse::_internal_cos_config() const {
  const ::drop::CosConfig* p = cos_config_;
  return p != nullptr ? *p : *reinterpret_cast<const ::drop::CosConfig*>(
      &::drop::_CosConfig_default_instance_);
}
inline const ::drop::CosConfig& FetchConfigResponse::cos_config() const {
  // @@protoc_insertion_point(field_get:init_svc.FetchConfigResponse.cos_config)
  return _internal_cos_config();
}
inline void FetchConfigResponse::unsafe_arena_set_allocated_cos_config(
    ::drop::CosConfig* cos_config) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config_);
  }
  cos_config_ = cos_config;
  if (cos_config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.FetchConfigResponse.cos_config)
}
inline ::drop::CosConfig* FetchConfigResponse::release_cos_config() {
  auto temp = unsafe_arena_release_cos_config();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::drop::CosConfig* FetchConfigResponse::unsafe_arena_release_cos_config() {
  // @@protoc_insertion_point(field_release:init_svc.FetchConfigResponse.cos_config)
  
  ::drop::CosConfig* temp = cos_config_;
  cos_config_ = nullptr;
  return temp;
}
inline ::drop::CosConfig* FetchConfigResponse::_internal_mutable_cos_config() {
  
  if (cos_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::drop::CosConfig>(GetArena());
    cos_config_ = p;
  }
  return cos_config_;
}
inline ::drop::CosConfig* FetchConfigResponse::mutable_cos_config() {
  // @@protoc_insertion_point(field_mutable:init_svc.FetchConfigResponse.cos_config)
  return _internal_mutable_cos_config();
}
inline void FetchConfigResponse::set_allocated_cos_config(::drop::CosConfig* cos_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config_);
  }
  if (cos_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config)->GetArena();
    if (message_arena != submessage_arena) {
      cos_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, cos_config, submessage_arena);
    }
    
  } else {
    
  }
  cos_config_ = cos_config;
  // @@protoc_insertion_point(field_set_allocated:init_svc.FetchConfigResponse.cos_config)
}

// string message = 3;
inline void FetchConfigResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FetchConfigResponse::message() const {
  // @@protoc_insertion_point(field_get:init_svc.FetchConfigResponse.message)
  return _internal_message();
}
inline void FetchConfigResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:init_svc.FetchConfigResponse.message)
}
inline std::string* FetchConfigResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:init_svc.FetchConfigResponse.message)
  return _internal_mutable_message();
}
inline const std::string& FetchConfigResponse::_internal_message() const {
  return message_.Get();
}
inline void FetchConfigResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FetchConfigResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:init_svc.FetchConfigResponse.message)
}
inline void FetchConfigResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:init_svc.FetchConfigResponse.message)
}
inline void FetchConfigResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:init_svc.FetchConfigResponse.message)
}
inline std::string* FetchConfigResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FetchConfigResponse::release_message() {
  // @@protoc_insertion_point(field_release:init_svc.FetchConfigResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FetchConfigResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:init_svc.FetchConfigResponse.message)
}
inline std::string* FetchConfigResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:init_svc.FetchConfigResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FetchConfigResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:init_svc.FetchConfigResponse.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace init_svc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_init_2eproto
