// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: hotmethod.proto

package hotmethod

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hotmethod_Collect_FullMethodName      = "/hotmethod.Hotmethod/Collect"
	Hotmethod_NotifyResult_FullMethodName = "/hotmethod.Hotmethod/NotifyResult"
)

// HotmethodClient is the client API for Hotmethod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hotmethod 服务：负责任务下发和结果回报。
// Collect 由 Server 主动推送给 Agent（同步下发，备用路径）。
// NotifyResult 由 Agent 在采集完成后主动上报给 Server。
type HotmethodClient interface {
	Collect(ctx context.Context, in *Target, opts ...grpc.CallOption) (*empty.Empty, error)
	NotifyResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*empty.Empty, error)
}

type hotmethodClient struct {
	cc grpc.ClientConnInterface
}

func NewHotmethodClient(cc grpc.ClientConnInterface) HotmethodClient {
	return &hotmethodClient{cc}
}

func (c *hotmethodClient) Collect(ctx context.Context, in *Target, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Hotmethod_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotmethodClient) NotifyResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Hotmethod_NotifyResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotmethodServer is the server API for Hotmethod service.
// All implementations must embed UnimplementedHotmethodServer
// for forward compatibility.
//
// Hotmethod 服务：负责任务下发和结果回报。
// Collect 由 Server 主动推送给 Agent（同步下发，备用路径）。
// NotifyResult 由 Agent 在采集完成后主动上报给 Server。
type HotmethodServer interface {
	Collect(context.Context, *Target) (*empty.Empty, error)
	NotifyResult(context.Context, *TaskResult) (*empty.Empty, error)
	mustEmbedUnimplementedHotmethodServer()
}

// UnimplementedHotmethodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotmethodServer struct{}

func (UnimplementedHotmethodServer) Collect(context.Context, *Target) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedHotmethodServer) NotifyResult(context.Context, *TaskResult) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyResult not implemented")
}
func (UnimplementedHotmethodServer) mustEmbedUnimplementedHotmethodServer() {}
func (UnimplementedHotmethodServer) testEmbeddedByValue()                   {}

// UnsafeHotmethodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotmethodServer will
// result in compilation errors.
type UnsafeHotmethodServer interface {
	mustEmbedUnimplementedHotmethodServer()
}

func RegisterHotmethodServer(s grpc.ServiceRegistrar, srv HotmethodServer) {
	// If the following call panics, it indicates UnimplementedHotmethodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hotmethod_ServiceDesc, srv)
}

func _Hotmethod_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotmethodServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotmethod_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotmethodServer).Collect(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hotmethod_NotifyResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotmethodServer).NotifyResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hotmethod_NotifyResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotmethodServer).NotifyResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// Hotmethod_ServiceDesc is the grpc.ServiceDesc for Hotmethod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hotmethod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hotmethod.Hotmethod",
	HandlerType: (*HotmethodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Collect",
			Handler:    _Hotmethod_Collect_Handler,
		},
		{
			MethodName: "NotifyResult",
			Handler:    _Hotmethod_NotifyResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotmethod.proto",
}
