// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hotmethod.proto

package hotmethod

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	drop "minidrop/apiserver/proto/drop"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskDesc 完整描述一个采集任务，由 Server 通过心跳响应下发给 Agent。
type TaskDesc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                       // 全局唯一任务 ID，由 apiserver 生成
	TaskType      uint32                 `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`                // 任务类型：0=通用CPU / 1=Java / 2=Tracing / 4=内存 / 6=JavaHeap
	ProfilerType  uint32                 `protobuf:"varint,3,opt,name=profiler_type,json=profilerType,proto3" json:"profiler_type,omitempty"`    // 采集器类型：0=perf / 1=async-profiler / 2=pprof
	SampleArgv    *RecordArgv            `protobuf:"bytes,4,opt,name=sample_argv,json=sampleArgv,proto3" json:"sample_argv,omitempty"`           // 采样参数
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`  // 容器或 Pod 名称（非容器场景留空）
	ContainerType uint32                 `protobuf:"varint,6,opt,name=container_type,json=containerType,proto3" json:"container_type,omitempty"` // 容器类型：0=无 / 1=Docker / 2=K8s Pod
	TimeoutSec    uint32                 `protobuf:"varint,7,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`          // 任务超时秒数，超时后 Agent 强制终止子进程
	CosConfig     *drop.CosConfig        `protobuf:"bytes,8,opt,name=cos_config,json=cosConfig,proto3" json:"cos_config,omitempty"`              // 对象存储凭证，Agent 用它上传结果
	ScriptContent string                 `protobuf:"bytes,9,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`  // 仅 ScriptExec 任务使用，其他任务留空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDesc) Reset() {
	*x = TaskDesc{}
	mi := &file_hotmethod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDesc) ProtoMessage() {}

func (x *TaskDesc) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDesc.ProtoReflect.Descriptor instead.
func (*TaskDesc) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDesc) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskDesc) GetTaskType() uint32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TaskDesc) GetProfilerType() uint32 {
	if x != nil {
		return x.ProfilerType
	}
	return 0
}

func (x *TaskDesc) GetSampleArgv() *RecordArgv {
	if x != nil {
		return x.SampleArgv
	}
	return nil
}

func (x *TaskDesc) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *TaskDesc) GetContainerType() uint32 {
	if x != nil {
		return x.ContainerType
	}
	return 0
}

func (x *TaskDesc) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskDesc) GetCosConfig() *drop.CosConfig {
	if x != nil {
		return x.CosConfig
	}
	return nil
}

func (x *TaskDesc) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

// RecordArgv 是传给 perf / async-profiler / pprof 等工具的采样参数。
type RecordArgv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hz            uint32                 `protobuf:"varint,1,opt,name=hz,proto3" json:"hz,omitempty"`                 // 采样频率（Hz），例如 99
	Duration      uint64                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`     // 采集时长（秒），例如 30
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`               // 目标进程 PID，-1 表示全系统采样
	Callgraph     string                 `protobuf:"bytes,4,opt,name=callgraph,proto3" json:"callgraph,omitempty"`    // 调用图模式：fp（帧指针）/ dwarf / lbr
	Subprocess    bool                   `protobuf:"varint,5,opt,name=subprocess,proto3" json:"subprocess,omitempty"` // 是否同时采集目标进程的子进程
	Event         string                 `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`            // 采样事件，例如 cpu-cycles / cache-misses（留空用默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordArgv) Reset() {
	*x = RecordArgv{}
	mi := &file_hotmethod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordArgv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordArgv) ProtoMessage() {}

func (x *RecordArgv) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordArgv.ProtoReflect.Descriptor instead.
func (*RecordArgv) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{1}
}

func (x *RecordArgv) GetHz() uint32 {
	if x != nil {
		return x.Hz
	}
	return 0
}

func (x *RecordArgv) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecordArgv) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RecordArgv) GetCallgraph() string {
	if x != nil {
		return x.Callgraph
	}
	return ""
}

func (x *RecordArgv) GetSubprocess() bool {
	if x != nil {
		return x.Subprocess
	}
	return false
}

func (x *RecordArgv) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

// Target 是 Collect RPC 的请求体，指定采集目标。
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskDesc      *TaskDesc              `protobuf:"bytes,2,opt,name=task_desc,json=taskDesc,proto3" json:"task_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_hotmethod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Target) GetTaskDesc() *TaskDesc {
	if x != nil {
		return x.TaskDesc
	}
	return nil
}

// TaskResult 是 Agent 采集完成后上报的结果。
type TaskResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                         // 对应的任务 ID
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // 空字符串表示成功，否则为错误原因
	File           *drop.File             `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`                                           // 内联小文件（结果较小时使用）
	CosKey         string                 `protobuf:"bytes,4,opt,name=cos_key,json=cosKey,proto3" json:"cos_key,omitempty"`                         // 对象存储路径，例如 /tid/perf.data
	SelfPstats     []*drop.PidStats       `protobuf:"bytes,5,rep,name=self_pstats,json=selfPstats,proto3" json:"self_pstats,omitempty"`             // Agent 自身的资源历史（时序）
	ChildrenPstats []*drop.PidStats       `protobuf:"bytes,6,rep,name=children_pstats,json=childrenPstats,proto3" json:"children_pstats,omitempty"` // 子进程的资源历史（时序）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_hotmethod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetFile() *drop.File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *TaskResult) GetCosKey() string {
	if x != nil {
		return x.CosKey
	}
	return ""
}

func (x *TaskResult) GetSelfPstats() []*drop.PidStats {
	if x != nil {
		return x.SelfPstats
	}
	return nil
}

func (x *TaskResult) GetChildrenPstats() []*drop.PidStats {
	if x != nil {
		return x.ChildrenPstats
	}
	return nil
}

var File_hotmethod_proto protoreflect.FileDescriptor

const file_hotmethod_proto_rawDesc = "" +
	"\n" +
	"\x0fhotmethod.proto\x12\thotmethod\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe3\x02\n" +
	"\bTaskDesc\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\rR\btaskType\x12#\n" +
	"\rprofiler_type\x18\x03 \x01(\rR\fprofilerType\x126\n" +
	"\vsample_argv\x18\x04 \x01(\v2\x15.hotmethod.RecordArgvR\n" +
	"sampleArgv\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12%\n" +
	"\x0econtainer_type\x18\x06 \x01(\rR\rcontainerType\x12\x1f\n" +
	"\vtimeout_sec\x18\a \x01(\rR\n" +
	"timeoutSec\x12.\n" +
	"\n" +
	"cos_config\x18\b \x01(\v2\x0f.drop.CosConfigR\tcosConfig\x12%\n" +
	"\x0escript_content\x18\t \x01(\tR\rscriptContent\"\x9e\x01\n" +
	"\n" +
	"RecordArgv\x12\x0e\n" +
	"\x02hz\x18\x01 \x01(\rR\x02hz\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x04R\bduration\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1c\n" +
	"\tcallgraph\x18\x04 \x01(\tR\tcallgraph\x12\x1e\n" +
	"\n" +
	"subprocess\x18\x05 \x01(\bR\n" +
	"subprocess\x12\x14\n" +
	"\x05event\x18\x06 \x01(\tR\x05event\"S\n" +
	"\x06Target\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\ttask_desc\x18\x02 \x01(\v2\x13.hotmethod.TaskDescR\btaskDesc\"\xed\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\x04file\x18\x03 \x01(\v2\n" +
	".drop.FileR\x04file\x12\x17\n" +
	"\acos_key\x18\x04 \x01(\tR\x06cosKey\x12/\n" +
	"\vself_pstats\x18\x05 \x03(\v2\x0e.drop.PidStatsR\n" +
	"selfPstats\x127\n" +
	"\x0fchildren_pstats\x18\x06 \x03(\v2\x0e.drop.PidStatsR\x0echildrenPstats2\x80\x01\n" +
	"\tHotmethod\x124\n" +
	"\aCollect\x12\x11.hotmethod.Target\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\fNotifyResult\x12\x15.hotmethod.TaskResult\x1a\x16.google.protobuf.EmptyB$Z\"minidrop/apiserver/proto/hotmethodb\x06proto3"

var (
	file_hotmethod_proto_rawDescOnce sync.Once
	file_hotmethod_proto_rawDescData []byte
)

func file_hotmethod_proto_rawDescGZIP() []byte {
	file_hotmethod_proto_rawDescOnce.Do(func() {
		file_hotmethod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotmethod_proto_rawDesc), len(file_hotmethod_proto_rawDesc)))
	})
	return file_hotmethod_proto_rawDescData
}

var file_hotmethod_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hotmethod_proto_goTypes = []any{
	(*TaskDesc)(nil),       // 0: hotmethod.TaskDesc
	(*RecordArgv)(nil),     // 1: hotmethod.RecordArgv
	(*Target)(nil),         // 2: hotmethod.Target
	(*TaskResult)(nil),     // 3: hotmethod.TaskResult
	(*drop.CosConfig)(nil), // 4: drop.CosConfig
	(*drop.File)(nil),      // 5: drop.File
	(*drop.PidStats)(nil),  // 6: drop.PidStats
	(*empty.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_hotmethod_proto_depIdxs = []int32{
	1, // 0: hotmethod.TaskDesc.sample_argv:type_name -> hotmethod.RecordArgv
	4, // 1: hotmethod.TaskDesc.cos_config:type_name -> drop.CosConfig
	0, // 2: hotmethod.Target.task_desc:type_name -> hotmethod.TaskDesc
	5, // 3: hotmethod.TaskResult.file:type_name -> drop.File
	6, // 4: hotmethod.TaskResult.self_pstats:type_name -> drop.PidStats
	6, // 5: hotmethod.TaskResult.children_pstats:type_name -> drop.PidStats
	2, // 6: hotmethod.Hotmethod.Collect:input_type -> hotmethod.Target
	3, // 7: hotmethod.Hotmethod.NotifyResult:input_type -> hotmethod.TaskResult
	7, // 8: hotmethod.Hotmethod.Collect:output_type -> google.protobuf.Empty
	7, // 9: hotmethod.Hotmethod.NotifyResult:output_type -> google.protobuf.Empty
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hotmethod_proto_init() }
func file_hotmethod_proto_init() {
	if File_hotmethod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotmethod_proto_rawDesc), len(file_hotmethod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotmethod_proto_goTypes,
		DependencyIndexes: file_hotmethod_proto_depIdxs,
		MessageInfos:      file_hotmethod_proto_msgTypes,
	}.Build()
	File_hotmethod_proto = out.File
	file_hotmethod_proto_goTypes = nil
	file_hotmethod_proto_depIdxs = nil
}
